"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from .base import *


# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = '%xexkh8$o6)_ux$*u_q$)b8i+qr60qf8@nco%rz&6egr&=@%zy'
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# 发送邮件
EMAIL_PORT = 25
# 与SMTP服务器进行通信，是否启动TLS链接（安全链接）
EMAIL_USE_TLS = True